### ISSUE TITLE
Chr prefix

### ISSUE THREAD

**Issue by yloemie** [deeptools/deepTools#1006]
Hi team,

I have an issue : I have aligned chip-seq data simultaneously on Drosophila and Mouse (spike-in method). Now I want to recover my bigwig and I masked the Drosophila genome with the blacklist. The problem is my mouse chrX is called chrX and in Drosophila just X. The blacklist region is confused and masked both the drosophila X chromosome and the beginning of the mouse chrX chromosome (same comportment on Y chromosome). Anyway I can handle by changing the bam header but it take me some time to understand why and there is no information about this modification of prefix in the bamCoverage manual.

thanks,

Yann

Python 2.7.17
deeptools 3.3.1

**Comment by friedue** [comment]
That's a service of deepTools turning against you for a change :) Many tools fail when the chromosome names are not matched due to the presence or absence of "chr", so deepTools takes care of that, i.e. treating "chrX" and "X" as the same chromosome. Generating a bigWig with mixed species is an unusual use case and potentially dangerous here as there will, indeed, be no distinction made between the reads for "chrX" and "X".

I recommend to generate separate bigWigs for Drosophila and Mouse separately (just subset the BAM file and blacklist regions). Otherwise you need to come up with a different nomenclature, e.g. "mmChrX" and "dmChrX", but I doubt that just changing the BAM Header will suffice.

**Comment by yloemie** [comment]
Thanks, I will change my bam files but it was for your interest.

anyways thanks for your works !

Yann
