### ISSUE TITLE
alignmentSieve changes the CIGAR (ignoring S and I)

### ISSUE THREAD

**Issue by alexyfyf** [deeptools/deepTools#1023]
Hi team,

I need some help with alignmentSieve here.

```
deeptools 3.5.0
python 3.6.7

(/home/fyan0011/mx82/fyan0011/conda_env/rnasik-1.5.4) [fyan0011@m3a010 test]$ samtools view test.bam| head -n2
A00611:41:HV32JDRXX:1:2229:24469:8954   163     1       3000066 40      58M2S   =       3000395 388     GAACTCTGCATTAAACCCATCTGGTCCTGGGCTTTTTTTTTTTTTTTTTTTTTTTTTTTT    FFFFFFFFFFFF:FFFFFFFFFFFFFFFFFFFFF:FFFFFFFFFFF,,FF::,FFFFF,F MC:Z:59M        MD:Z:58 PG:Z:MarkDuplicates     NM:i:0  AS:i:58 XS:i:60
A00611:41:HV32JDRXX:1:2229:24469:8954   83      1       3000395 40      59M     =       3000066 -388    TAAGGGTTTATCTATCTTGTTGACTTTCTCAAAGAACCAGCTACTAGTTTGGTTGATTC     F:FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF  MC:Z:58M2S      MD:Z:46T12      PG:Z:MarkDuplicates     NM:i:1  AS:i:54 XS:i:54
(/home/fyan0011/mx82/fyan0011/conda_env/rnasik-1.5.4) [fyan0011@m3a010 test]$ samtools view filtered.sorted.bam| head -n2
A00611:41:HV32JDRXX:1:2229:24469:8954   163     1       3000070 40      54M     =       3000395 379     *       *
A00611:41:HV32JDRXX:1:2229:24469:8954   83      1       3000395 40      54M     =       3000070 -379    *       *
```
The shifted reads have correct coordinates, but the CIGAR should be 54M2S, in theory it should make no difference, because softclipping should be ignored anyway.
But I found in this issue #987 , the insertion is also removed. But I'm not sure about other events. 
How alignmentSieve deal with other CIGARs?

Cheers,

**Comment by dpryan79** [comment]
You'll note that we remove the sequence when we shift the reads, so a CIGAR of 54M2S would be incorrect as there's nothing left to soft-clip. Likewise insertions may or may not make any sense after shifting (Can you shift off the first N bases of an insertion? Would it make sense to do so?), so since the sequence is stripped out anyway, InDels can be excluded from the CIGAR.

**Comment by alexyfyf** [comment]
Thanks @dpryan79 , I think my understanding is a bit different as to how the 'shift' works. 
Indeed, if you are talking about shifting a read, the indels in CIGAR makes no sense. 
But actually, in the case of ATAC shift, we would like to adjust the 5' of the reads/fragments. And this is achieved by chopping 4 or 5 bases from both ends of the fragment because Tn5 will repair the cutting site and create a 9 bp duplication, so the fragment end is not the actually Tn5 cutting site. 
So essentially, it is more like a 'trim' instead of a 'shift'. If that's the case, the CIGAR will remain sensible, but just removing the CIGAR for the first few bases.
Does that make sense to you? Anyway, it should make no big difference, just my opinion for improvement. 
I used to use this script https://github.com/TheJacksonLaboratory/ATAC-seq/blob/master/auyar/ATAC_BAM_shifter_gappedAlign.pl to shift the reads, and now I'm turning to deeptools as it integrates a lot of other functions. 

Cheers,

**Comment by dpryan79** [comment]
I'm fully aware of the misplaced point of "shifting" in ATAC-seq (it's actually to account for the resulting ssDNA overhand produced by Tn5, which is of highly questionable utility). We do indeed not account for insertions at the beginning of reads and completely rewrite CIGAR strings to have only matches. The former is due to the rarity of this happening, the latter due to the CIGAR string rarely being used in any meaningful way downstream. If people are actually producing datasets where this makes a tangible difference then I'd be happy to change it, but otherwise there's little reason to add notable technical debt to an already large code-base.

**Comment by alexyfyf** [comment]
Thank you so much, you are right I don't see a problem now or anywhere soon. 
I will close it.
