### ISSUE TITLE
question on reads extension ?

### ISSUE THREAD

**Issue by nservant** [deeptools/deepTools#1024]
Hi all,

I do have a small question on read extension parameter for ChIP-seq and ATAC-seq data.

About ChIP-seq first, could you please confirm me that even for paired-end data, we have to specify the `--extendReads` parameter to use fragments instead of reads ? It is not that clear if fragments are automatically recognized or not for paired-end ?

Then, for ATAC-seq, I was just wondering what are the good practices for read extension ?

Many thanks

**Comment by dpryan79** [comment]
For ChIP-seq it's best to use extendReads so you see the full fragment coverage. Note that if you don't do any normalization of the bigWig file, then you'll want to exclude either read 1 or 2 (otherwise the extended fragments from both will get used and these will be the same 99.9% of the time). If you do any normalization of the BigWig file then this isn't an issue.

For ATAC-seq it kind of depends on what you want to do. Generally people want to know where Tn5 has access, in which you don't want to extend reads (in fact you really only want the first ~15-20 bases of each read, since that's actually the accessible region).

**Comment by nservant** [comment]
Thanks Devon.

For ChIP-seq it's best to use extendReads so you see the full fragment coverage. Note that if you don't do any normalization of the bigWig file, then you'll want to exclude either read 1 or 2 (otherwise the extended fragments from both will get used and these will be the same 99.9% of the time). If you do any normalization of the BigWig file then this isn't an issue.

Just to be sure, it means that for instance `bamCoverage --extendReads` with paired-end data, does the extension from both read 1 and 2 ? Does it mean that the `extendReads` option should be not used for paired-end ? Regarding normalization, I'm usually computing a scaling factor `10000000/$aligned_reads` and use `--scaleFactor`

Thanks

**Comment by dpryan79** [comment]
Correct, by default it will extend both reads, which will double the number of fragments you see. You should still use that option with PE data, just use some sort of normalization (what you showed is reasonable). There are some use-cases where you want the bigWig to show exact read fragment counts, so this doubling of the signal is really only an issue there.
