### ISSUE TITLE
Arrange the size of subplots in plotHeatmap deeptools figure

### ISSUE THREAD

**Issue by kinali** [deeptools/deepTools#1050]
Hi all,

I am trying to generate a 10x10 (10 bw files + 10 bed files) figure using deeptools but I am having trouble arranging the size of subfigures. I want the subfigures in the same size but if I use plotHeatmap figure heights are changing. If I use plotProfile, I can get the subfigures with the same height and width but it produces a 1X10 figure, not a 10X10 figure. Also, I cannot change the color of the plotProfile heatmap and I read that the feature will be in the next release.

In this case, I need to use plotHeatmap and fix the size of each subplot. I have checked previous issues before and the most similar case to mine is this https://github.com/deeptools/deepTools/issues/993 but this does not help too. I also post this question here too https://www.biostars.org/p/496494/

I would appreciate any help!

**Comment by LeilyR** [comment]
from version  >=3.5 should be possible to se colors for plotProfile --plotType heatmap. Which version are you using ? Have you try this on 3.5 and did not work?

**Comment by LeilyR** [comment]
As far as I understood it was intentional to produce 1*10 instead of 10*10. This was to avoid the confusion between having several groups of regions or only one group of regions. If you are interested in that, you can generate smaller matrices (subset of your bigwig files), make the heatmap and manually align them underneath each other.

**Comment by kinali** [comment]
Thank you, I updated deeptools and changed colors as you suggested.
