### ISSUE TITLE
Need for more function in deeptools

### ISSUE THREAD

**Issue by frylhc** [deeptools/deepTools#1054]
Hi Devon and everyone! I am using deeptools 3.5.1 computeMatrix and plotProfile to visulize WGBS data. With these  two function, I could plot DNA methylation profiles that is universally presented in most articles. I have three questions.
1.  I am trying to figure out whether or not could deeptools plot more sophisticated profiles. Could deeptools recognize, scale and bin different exons and introns seperately and plot these infromation matrix in one profile? Like this one in a research article. https://github.com/lyijin/pdae_dna_meth/blob/master/descriptive/genomic_context/meth_levels.across_gene.pdf
2. I plotted the profiles using bam files aligned and deduplicated by Bismark, then the yaxis should stand for averaged DNA methylation levels per bin, am I right? Could deeptools plot profiles that the yaxis stand for DNA methylation density? If could, how could I do this?
3. I do not understand the argument --nanAfterEnd under the reference_point mode, I have plotted both with and without the arguement, different profiles are plotted, but I do not understand how the argument result two different profiles.
Please forgive me for so many questions. Thanks for your time and attention.

**Comment by dpryan79** [comment]
1. You can't scale different exons separately in deepTools and I don't think we want to add that functionality (at least I'm not interested in adding that, since it's too project-specific to make it worthwhile).
2. If you make a bigWig file containing methylation metrics then you can use it in deepTools. I've done this in the past, with the main issue being that the data tend to be really sparse. If you work on something with a small and dense genome then this is probably less of an issue.
3. Suppose you use start as a reference point and choose to plot 2kb downstream. If a region in your BED/GTF file is less than 2kb, then you need to decide what to do with the data that falls outside of the region. By default it's included. If, however, you're looking at a signal that you expect to change at the end of a gene (or whatever your regions represent) then `--nanAfterEnd` will maintain that information, as all data falling outside of the gene gets converted to `NaN` and therefor plotted in a different color. This sort of thing is easier to see if you then sort by region_length (in fact if you do use nanAfterEnd you really should also sort by region length for the clearest results.

**Comment by frylhc** [comment]
I understand. Will try what you suggested about the --nanAfterEnd argument.Thanks for your time.

**Comment by frylhc** [comment]
Hi, Devon. Got questions again. I am still confused with the y-axis of my plot. I have converted bismark output files (in bam format) to bigwig files using deeptools bamCoverage, and then using computeMatrix to generate the matrix, finally plotted the profile. Below is the profiles I got. I am confused about the y-axis. My questions are listed below:
Q1: Bigwig files converted from bismark bam files using bamCoverage show us the information of the sequenced read coverage across the entire genome, am I right? I have load bigwig files in genome browser.
Q2:  What does matrix generated from bigwig files using computeMatrix tells us? The average of read coverage within each bin or DNA methylation level?
Q3: Below is the profiles I got, I don't understand what the y-axis means here. With one peak at TSS and TES respectively, I don't thinks y-axis should stand for read coverage,since both library preparation and sequencing processes are generally random，it is unlikely that reads around TSS and TES get more chances to be sequenced than other genomic features. Am I right or wrong?
Q4: If the y-axis represents DNA methylation levels, at which step do information from bam files converted into DNA methylation level? And how did this achieved?
BTW, I am working on a small and compact genome. Again, forgive me for so many questions. Thanks again.
![image](https://user-images.githubusercontent.com/68120639/118910989-ff36b200-b957-11eb-94b3-907ca3def29e.png)

**Comment by dpryan79** [comment]
1. If you used bamCoverage then the bigWig files contain read coverage information. This is likely not what you're interested in looking at give the type of data you have.
2. Since the bigWigs seem to contain coverage information, the access is "average coverage". The increase in coverage at the TSS is likely due to a slight bias that occurs during library prep (e.g., TSS regions have a different GC content, so the PCR amplification step will lead to a slight skew in coverage there).
