### ISSUE TITLE
alignmentSieve --ATACshift output BAMs size and possible error

### ISSUE THREAD

**Issue by SergioRLL** [deeptools/deepTools#1205]
Hello,

I wanted to use `alignmentSieve` to shift the reads of my ATACseq pipeline using the `--ATACshift` parameter. 
```
> for f in $READS/C1/*.bam
> do
>         name="${f##*/}"
>         name="${name%.*}"
>         alignmentSieve -b $f --numberOfProcessors max --ATACshift -o $SHIFTED/C1/$name.shifted.bam
> done
```

It executed displaying error lines like these: 
```
[E::idx_find_and_load] Could not retrieve index file for '/scratch/tmp/21237817/_deeptools_q_1ia6tz.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/tmp/21237817/_deeptools_obw5vdny.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/tmp/21237817/_deeptools_o52gi83v.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/tmp/21237817/_deeptools_8i91fzn5.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/tmp/21237817/_deeptools_ifv8bsei.bam'
[E::idx_find_and_load] Could not retrieve index file for '/scratch/tmp/21237817/_deeptools_sn5vcqac.bam'
...
```
Versions:
```
deeptools 3.3.0
alignmentSieve 3.3.0
Python 3.6.5
```
Those filenames in the error don't match the actual names, I guess they may be intermediate files created by deeptools?
However I still got output BAMs so I guess it worked and the previous message were actually warnings of some kind?
My concern also comes because **the size of the output BAMs are about twice the size of the input ones**. Does this make sense given that the command I used was only meant to shift the reads?
I also run the above command using the `--BED` option and the BEDPE files were generated without any trouble.
Regarding the output BAMs I don't get why their size is much larger than the input ones.

Thank you in advance of the help!

**Comment by WardDeb** [comment]
Hiya,

Regarding the first question, these index errors (warnings) can be safely ignored (are introduced in HTSlib > 1.10, see https://github.com/pysam-developers/pysam/issues/939). These should be suppressed now in the upcoming version (develop branch for now).

Regarding the output size, that was expected behavior as well, since alignmentSieve wrote out uncompressed bam files. This should also be taken care of in the upcoming version.

Hope this helps, if not feel free to re-open !

Kind regards,

wardDeb
