### ISSUE TITLE
plotHeatmap discrepancy

### ISSUE THREAD

**Issue by brimittleman** [deeptools/deepTools#670]
I am mapping reads to 5' and 3' splice boundaries using the computeMatrix and plotheatmap functions. My enrichment plots do not seem to match the pattern in the heat maps. Have you seen this before and if so is there a reason for it?  

![net-seq-5prime-18486](https://user-images.githubusercontent.com/22207447/36517913-d70370ba-1749-11e8-8fbd-5137f3314a19.png)
![net-seq-3prime-18486](https://user-images.githubusercontent.com/22207447/36517916-dac6d39a-1749-11e8-957e-f99a1c18e718.png)

**Comment by dpryan79** [comment]
That's a new one, would it be possible to make the bigWig and BED files available to see if we can reproduce this? What version of deepTools are you using?

**Comment by brimittleman** [comment]
I am using 3.0.0 from bioconda. I can upload the data to a google drive, is there an email I can share it with?

**Comment by dpryan79** [comment]
Please share it with dpryan79@gmail.com, thanks!

**Comment by brimittleman** [comment]
Done. Thanks for your help.

**Comment by dpryan79** [comment]
I'll have a look tomorrow morning (my time) and see if I can track this down.

**Comment by dpryan79** [comment]
It turns out that the profile plot at the top is correct, the disconnect between that and the heatmap is due to a couple factors. The biggest of these is that the heatmap range is shrunken to remove the top 2% of values. The vast majority of the data is between 0 and 1, but you have a small number of entries with very very large values. These are then skewing the average heavily. You could take the median, but as you have a huge number of entries of all 0s you'll then end up with a flat line. You can try using `--skipZeros` in `computeMatrix`, possibly with `--averageTypeSummaryPlot median`. Some combination of that plus either k-means clustering and/or filtering will allow the two plots to be more congruent. In general, though, there's no good way to make a heatmap of that many values, particularly when the span the range from 0 to 100,000, when the majority near 0.
