### ISSUE TITLE
plotHeatmap dotted line of feature length should be adjusted when using --referencePoint center

### ISSUE THREAD

**Issue by guillaumecharbonnier** [deeptools/deepTools#671]
Plotting a dotted line showing the feature length when using "--sortUsing region_length" in plotHeatmap" is great but the length it displays should be halfed when used with "--referencePoint center".

Example with  "--referencePoint center" => not ok
![image](https://user-images.githubusercontent.com/20519429/36537529-b87019aa-17d0-11e8-95fa-a486e8b45e62.png)

Example with " "--referencePoint TSS" => ok
![image](https://user-images.githubusercontent.com/20519429/36537549-caf8f542-17d0-11e8-8964-0ef97d46cb23.png)

**Comment by dpryan79** [comment]
Good point, I don't think we'd considered this use case.

**Comment by dpryan79** [comment]
It turns out that fixing this wasn't too hard. While I was at it, I made it so that one can also get the dotted line at the TSS if one uses `--referencePoint TES`. It might be nice to have two lines with `--referencePoint center`, but since it's symmetric that's probably not really needed. I'll put this fix in version 3.0.2, which will presumably come out at the beginning of April. If you need it sooner, then go ahead and install the `develop` branch from github.
