### ISSUE TITLE
How does deeptools computeMatrix work？

### ISSUE THREAD

**Issue by werhoog** [deeptools/deepTools#682]
I already knew that " deeptools computeMatrix" can creat a matrix for plot.When I plot by plotProfile , I can not understand that what Y-axis means. Is it refers the score or the read counts of the bw files across per bin?? How " deeptools computeMatrix" fix different length of region of the bed file to creat a matrix ?

THANKS !!!

**Comment by dpryan79** [comment]
The Y axis is in whatever unit the bigWig files are in. All that compute matrix does is go over a set of regions and bigwig files. Let's take the example of scale-regions and look at what happens for a single region in a single bigWig file:

1.. Divide the "gene body length" by the "bin size", this is then the number of bins that we need to compute values for in each region. This only needs to be done once.
2. Extract all of the per-base values in the region.
3. Divide the per-base values in step 1 into the number of bins determined in step 1.
4. Inside each subset of values in step 3 compute the average
5. Save that to a file

Note that step 3 ends of "scaling the regions", since every region, regardless of its actual length, ends up getting scaled to the same size. To make things more concrete, let's assume we run computeMatrix with a bin size of 50 and a gene body size of 500. That means that we'll end up computing `500/50=10` bins worth of values, regardless of the size of an individual region. For a region of 500 bases, each of these bins will hold the average value from 50 bases of data. If a region is 2000 bases, then each bin will hold the average of `2000/10=200 bases` worth of data.

For plotProfile (or the profile plot output by plotHeatmap), the values are then the average in each bin across regions. Since each region is scaled to the exact same number of bins, you can imagine these stacked on top of each other vertically (see the heatmap from plotHeatmap) and then the average of each column calculated and plotted. Importantly, if you have outlier values then they can heavily skew this plot. For that reason it's often useful to look at both the profile and a heatmap, as provided by plotHeatmap.

**Comment by werhoog** [comment]
Wow，It is a perfect answer to my problem. Thanks a lot !






At 2018-03-05 22:59:44, "Devon Ryan" <notifications@github.com> wrote:


The Y axis is in whatever unit the bigWig files are in. All that compute matrix does is go over a set of regions and bigwig files. Let's take the example of scale-regions and look at what happens for a single region in a single bigWig file:

1.. Divide the "gene body length" by the "bin size", this is then the number of bins that we need to compute values for in each region. This only needs to be done once.
2. Extract all of the per-base values in the region.
3. Divide the per-base values in step 1 into the number of bins determined in step 1.
4. Inside each subset of values in step 3 compute the average
5. Save that to a file

Note that step 3 ends of "scaling the regions", since every region, regardless of its actual length, ends up getting scaled to the same size. To make things more concrete, let's assume we run computeMatrix with a bin size of 50 and a gene body size of 500. That means that we'll end up computing 500/50=10 bins worth of values, regardless of the size of an individual region. For a region of 500 bases, each of these bins will hold the average value from 50 bases of data. If a region is 2000 bases, then each bin will hold the average of 2000/10=200 bases worth of data.

For plotProfile (or the profile plot output by plotHeatmap), the values are then the average in each bin across regions. Since each region is scaled to the exact same number of bins, you can imagine these stacked on top of each other vertically (see the heatmap from plotHeatmap) and then the average of each column calculated and plotted. Importantly, if you have outlier values then they can heavily skew this plot. For that reason it's often useful to look at both the profile and a heatmap, as provided by plotHeatmap.
