### ISSUE TITLE
Problem with -bl and --normalizeUsing options

### ISSUE THREAD

**Issue by endicytosis** [deeptools/deepTools#701]
Hi guys, I am having a problem running -bl and --normalizeUsing options together. I can do one or the other, but not together. Has anyone experienced this problem before?
This is an example of my code:
`bamCoverage --bam Sample_0.bam -o Sample_0.bw \`
`  -bl mm10.blacklist.bed \`
`  --effectiveGenomeSize 2652783500 \`
`  --normalizeUsing RPGC \`
`  --binSize 10 \`
`  --ignoreForNormalization chrX \`

That command gives me:
`Your blacklist file(s) has (have) regions that overlap. Proceeding with such a file would result in deepTools incorrectly calculating scaling factors. As such, you MUST fix this issue before being able to proceed.`

Thanks a bunch!

**Comment by dpryan79** [comment]
Remove the overlapping regions in your BED file, as the error message indicated, and everything will work. This error occurs because the computation of 1x/RPGC coverage involves subtracting the reads from blacklisted regions. The computation of the number of reads in blacklisted regions involves calculating the number of reads in each one. We had previously noted that some of the 1x normalization tracks were wrong (with negative values, which were impossible) due people using poorly formed blacklist files. This error is meant to prevent that sort of thing.

I addition to merging overlapping regions, encourage you to manually look at those regions against a few tracks in IGV. It will likely then be clear that you should merge some of the non-overlapping tracks together as well.
