### ISSUE TITLE
--metagene does not work for bed12 file provided

### ISSUE THREAD

**Issue by MengjunWu** [deeptools/deepTools#708]
Hi, 
I was trying to plot RNAseq with the --metagene option, and provided bed12 file like following (I only plotted one region for sanity check):
chr1    1477053 1510249 ENSG00000160075.10      100     -       1477053 1510249 255,0,0 5       494,118,1849,2571,391   0,2196,2965,20672,32805

However in the final plot, it seems it did not remove the intron region and the plot still looked like spliced, any idea why was this?

Thank you!

Best,
Mengjun

**Comment by dpryan79** [comment]
What was the entire command used?

**Comment by MengjunWu** [comment]
I tried reference point and scale-region, the reference point command is:

computeMatrix reference-point --referencePoint TSS -b 1000 -a 10000 -S totalRNA_sorted_merged_plus.bw totalRNA_sorted_merged_minus.bw EGFP_totalRNA_sorted_merged_plus.bw EGFP_totalRNA_sorted_merged_minus.bw  -R deeptools_metagenes_sanity.bed --metagene --binSize 50 --skipZeros -o trial.mat.gz --outFileSortedRegions deeptools_metagenes_sanity.txt 

Thanks!

**Comment by dpryan79** [comment]
I can't reproduce this. I'm including an example bigWig and BED12 file in ![example.zip](https://github.com/deeptools/deepTools/files/2006127/example.zip).

With `computeMatrix reference-point -R genes.bed -S foo.bw -a 10000 -b 1000 --metagene -o foo.mat.gz` I get:
![foo](https://user-images.githubusercontent.com/6399000/40074645-74253f56-587a-11e8-839c-28b656de0419.png)

Without `--metagene` I get:
![foo2](https://user-images.githubusercontent.com/6399000/40074646-743f18b8-587a-11e8-95e9-282a337f794a.png)

This is as expected, since I gave the introns negative values.

**Comment by dpryan79** [comment]
Feel free to reopen this if you have a counter example.
