### ISSUE TITLE
x and y limits for plotCorrelation scatter plot

### ISSUE THREAD

**Issue by dpryan79** [deeptools/deepTools#709]
Instead of just a `--maxRange`, it'd be better to offer x and y axis limits.

**Comment by dpryan79** [comment]
This is now in `develop`.

**Comment by Xiaofei-git** [comment]
Also, do you think is it possible to plot based on the normalized read counts within a bin because every sample is different, e.g. library size?

**Comment by dpryan79** [comment]
I have a PR to fix the error you ran into. Regarding your second question, if you create normalized bigWig files (using RPGC in `bamCoverage`) and use those with `multiBamSummary` then the results will be properly normalized.

**Comment by dpryan79** [comment]
PR is short for a "pull request" on github. It's now been merged and will appear in the next release.

**Comment by dpryan79** [comment]
Correct, that's a bug in the current version. I'll release 3.1.2 when I'm back in the office on Monday.

**Comment by Xiaofei-git** [comment]
Thanks a lot!

**Comment by Xiaofei-git** [comment]
For the normalization, you said " if you create normalized bigWig files (using RPGC in bamCoverage) and use those with multiBamSummary then the results will be properly normalized". But, after generating the bigWig files, how can I pass them to multiBamSummary because "multiBamSummary bins" take bam files not bw format?

**Comment by dpryan79** [comment]
Try `multiBigwigSummary` instead.

**Comment by Xiaofei-git** [comment]
Thanks!
