### ISSUE TITLE
fileSortedRegions output from plotHeatmap orders clusters differently than heatmap image

### ISSUE THREAD

**Issue by mhayes8520** [deeptools/deepTools#717]
When running some analysis on the clusters resulting from plotHeatmap --kmeans, as output by --fileSortedRegions, I noticed that the clusters were numbered differently. More specifically, the clusters in the heatmap image were not ordered by the size of the cluster, while the clusters (named in column 13 of the fileSortedRegions output) were ordered by size of the cluster. 

[fileSortedRegions-k5.txt](https://github.com/deeptools/deepTools/files/2091806/fileSortedRegions-k5.txt)
![tf_signal-atnpas4peaks-k5](https://user-images.githubusercontent.com/40182684/41258256-701cfd44-6d84-11e8-8e88-d31979796020.png)

Note how in the heatmap there are more regions in cluster 3 than in cluster 4, but these two cluster numbers are switched in the fileSortedRegions file, as indicated by the fact that there are more members of cluster 3 than 4 in the .txt file. 

I think the ordering of clusters in the heatmap should be preserved in the fileSortedRegions output. Makes life much easier, especially with higher values of K.

**Comment by dpryan79** [comment]
That's odd, can you make the original output from `computeMatrix` available? That'll help in tracking this down.

**Comment by mhayes8520** [comment]
Thanks for the quick response. The original matrix is too large to upload here (57 Mb) - can I send it to you via email?

**Comment by dpryan79** [comment]
Yes, or upload it somewhere and send me a link (ryan@ie-freiburg.mpg.de)

**Comment by dpryan79** [comment]
I'm guessing what happened is that you're using the image from one run of plotHeatmap and the matrix file from another. Since this is k-means clustering, the results aren't deterministic, so you'll get somewhat different numbers of regions in each cluster every time you produce the heatmap. I've run this a few times and checked this with each run and I'm not able to reproduce the issue (i.e., the file from `--outFileSortedRegions` matches what's in the image).

BTW, the cluster ordering is by average value (cluster 1 has the highest average). I don't think that's actually documented anywhere.
