### ISSUE TITLE
Interpretation of computeMatrix results

### ISSUE THREAD

**Issue by foehnwind** [deeptools/deepTools#757]
Dear @dpryan79, thanks for developing the package. I'd like to make sure I understand the algorithm correctly.

Suppose we run computeMatrix in scale-regions mode, with parameters `--regionBodyLength` `--beforeRegionStartLength`, `--afterRegionStartLength`, and `--binSize`. According to @dpryan79 's reply (https://github.com/deeptools/deepTools/issues/682), the number of bins of gene body seems to be `--regionBodyLength` divided by `--binSize`. How about upstream and downstream regions? Do they have `--beforeRegionStartLength`/`--binSize` and `--afterRegionStartLength`/`--binsize` bins, respectively? 

Another question is about the y-axis of a profile plot. I assume it is the per-base coverage averaged over `--binSize`, and then averaged over all genes provided by `-R`, am I correct?

Thanks,

**Comment by dpryan79** [comment]
Yes, the number of upstream bins will be `--beforeRegionStartLenth/--binSize` and it's the same for `--afterRegionStartLength`.

The profiles have the averaged per-bin values. Typically bins themselves aren't average coverage, but "total number of reads" (if the reads are on average larger than the bins then this will be a bit less than average coverage).

**Comment by dpryan79** [comment]
I understand the confusion, each bin is a variable size dependent upon the size of each gene. The exact number of bins, however, is constant, since it's `regionBodyLength/binSize`. So those two options allow you to scale the size of the scaled gene and the granularity of the summarization within it.

**Comment by foehnwind** [comment]
Thanks, it's clear now.

**Comment by quiocarbajal** [comment]
Hi! Thanks for developing the package and for answering so many questions.
I computed a matrix with the following command :  
`computeMatrix reference-point -b 2000 -a 2000 --referencePoint center ...`   
Then I got the --outFileNameMatrix using `PlotHeatMap`. On that tsv file I have 800 columns with scores (which would correspond to a bin size of 5). However, the default binsize is 10, and indeed that seems to be the case according to the tsv header:  
  
> @{"upstream":[2000,2000],"downstream":[2000,2000],"body":[0,0],"bin size":[10,10],"ref point":["center","center"],"verbose":false,"bin avg type":"mean","missing data as zero":false,"min threshold":null,"max threshold":null,"scale":1,"skip zeros":false,"nan after end":false,"proc number":1,"sort regions":"descend","sort using":"mean","unscaled 5 prime":[0,0],"unscaled 3 prime":[0,0],"sample_labels":["WT_b1","KO_b1"],"group_labels":["genes"],"sample_boundaries":[0,400,800],"group_boundaries":[0,31913]}  
  
Is this expected behaviour? If so, could you clarify why I get 800 bins on a 4000 bp region with bin of 10?

PS: Should I actually post this on an independent issue?
