### ISSUE TITLE
plotHeatmap and BS data

### ISSUE THREAD

**Issue by guillaumecharbonnier** [deeptools/deepTools#777]
Approximately 9 months ago, I produced the heatmap on the right from Bisulfite-Seq data using "--missingDataColor 1". Today I am trying again with v3.1.3 and I get this white heatmap on the left (and sometimes small portion of color from the scale) using the same settings. 
![bs_plotheatmap_missingdatacolor_1](https://user-images.githubusercontent.com/20519429/47919823-b362b100-deb0-11e8-9305-412257f3922d.png)
Is it the new " --interpolationMethod" default that is messing with what I am trying to do? Do you see how to get the previous behavior using deepTools 3 or should I stay with deepTools 2 for this?

**Comment by dpryan79** [comment]
You're right that it's the interpolation method, though I'd still encourage you to stay with deepTools 3 rather than 2. It happens that the hard-coded value in deepTools 2 happened to be reasonable in this case, but that ends up not being universally true. That's why we added the option, since it turns out there's no one-size-fits-all optimal method.

**Comment by guillaumecharbonnier** [comment]
Thanks, I tried all methods and forcing 'nearest' produced heatmap similar (same?) as the one produced by v2.
Btw, there is a typo in ' --interpolationMethod' doc: "Be default"

**Comment by dpryan79** [comment]
I think nearest was the default previously. Thanks for pointing out the typo, I’ll have to fix that.
