### ISSUE TITLE
Improving documention for --regionsFileName etc

### ISSUE THREAD

**Issue by seb-mueller** [deeptools/deepTools#886]
First of all thanks for this nice tool. Reading the documentian and running some examples left me with a few questions though. I think the documentation could benefit from anwereing them, so I've listed them below. I'm new to this software, so the answer of some of them are probably somewhere buried:

In `computeMatrix` and other tools, one has to specify regions, such as with as for the `computeMatrix` example :

```
--regionsFileName File name or names, in BED or GTF format, ...
```

There are various options, such as BED3/6/12 and GTF.
However the [documentation](https://deeptools.readthedocs.io/en/develop/content/tools/computeMatrix.html#scale-regions) is unclear how they should look like and which columns are being used.

- For example what is the difference between BED3/6/12 references? Possible answer: Number of columns. This should probably go in the file format -> bed section
- Are columns 4-6 of BED6 being used at all? or just column 1-3, i.e. BED 3 and 6 given same results?
- Same for BED12 (but columns 4-12)
- More specifically to above, is strand information being used in BED6/12

- GTF should be included in the file-format documentation since not listed (along with minimal example)
- I had problems with GTF files since it seem to mistaken it for BED files:  How does the `-R` distinguish between the BED and GTF (file extension doesn't seem to work in my case).
- which columns are being taken into account for GTF
- How would GTF need to look like for `–metagene` analysis?
- As for the option in `computeMatrix` :

> --transcriptID 	When a GTF file is used to provide regions, only entries with this value as their feature (column 2) will be processed as transcripts. (Default: “transcript”)

Are you sure column 2 is correct rather than 3, according to GTF specs (which is Gff2) says column 2 is "source" and column 3 "feature". 
https://www.ensembl.org/info/website/upload/gff.html

Also at the start page, it says:
> deepTools is a suite of python tools particularly developed for the efficient analysis of high-throughput sequencing data, such as ChIP-seq, RNA-seq or MNase-seq.

It should be made clear which parameters to use for which case. Specifically, how is strand-specificity being handled in RNA-Seq data? An example RNA-Seq workflow would be nice (even without strand-specificity). How should bed/gtf file look like for RNA-Seq (e.g. to exclude introns).
In general there is not much RNA-Seq being described in the documentation given it is listed on the start page.

**Comment by dpryan79** [comment]
> GTF should be included in the file-format documentation since not listed (along with minimal example)

I would prefer to not give more examples of standard formats, people can find those with google.

> which columns are being taken into account for GTF

Assume that all of them are (like in various BED formats), though in practice the source, score and frame are ignored by deepTools since they're not relevant.

> How would GTF need to look like for –metagene analysis?

Like a standard GTF file, as defined here: https://www.ensembl.org/info/website/upload/gff.html

> Are you sure column 2 is correct rather than 3

Good catch, I must have been thinking in terms of the code, where it's column 2 due to there being a column 0. I'll fix that.

> It should be made clear which parameters to use for which case

It's impossible to document the appropriate settings for every conceivable use case. At some points users need to understand what their data looks like and how they want to process it.

I'll make a small update to handle some of these suggestions, thanks!

**Comment by seb-mueller** [comment]
Thanks for getting back.

>>which columns are being taken into account for GTF

>Assume that all of them are (like in various BED formats), though in practice the source, score and frame are ignored by deepTools since they're not relevant.

 Just to clarify:  That implies that BED 3 and 6 should give different results, since BED3 includes strand information but BED6 does not?

Also as a follow up question: The above corresponds to strand direction of the tested intervals. I'm also wondering how strand information of reads are handled. Say, the interval (e.g. a gene or peak) is on the +strand (as specified in the BED6 file), are only "+" stranded reads used for profiling are are "+" and "-" merged together? I assume the later since the coverage conversion should throw strand info away.

**Comment by dpryan79** [comment]
BED6 contains strand information, BED3 doesn't. The difference will be that some rows in the resulting matrix will be flipped around.

The strandedness of reads is ignored by default, since many (probably still most except RNA-seq) protocols aren't strand-specific and the bigWig and bedGraph formats lack a way to store per-strand values. There is a `--filterRNAstrand` option so one can make a bigWig or bedGraph of only the + or - strand. That's usually enough for things like IGV. Getting the strand-specificity in plotHeatmap is a bit more involved (you can find instructions in the deepTools mailing list if you need them, it's "just" a few extra steps).
