### ISSUE TITLE
bamCompare v2.4.2 warning, not present in v3.3.1, is it fixed?

### ISSUE THREAD

**Issue by kimj50** [deeptools/deepTools#944]
Hi,
I'm a student learning to analyze ChIP data.
We just moved from older version (2.4.2) to newer (3.3.1). 
The older version bamCompare wiki had the following warning:
"The filtering by deepTools is done after the scaling factors are calculated!"
source: http://gensoft.pasteur.fr/docs/deepTools/2.4.2/content/tools/bamCompare.html

However, this warning is not present in 3.3.1, does this mean now filtering (ignoreduplicate and minmappingquality) are applied BEFORE the scaling factors are calculated?

Thank you - Jun

**Comment by dpryan79** [comment]
Yes, this was changed for the 3.0.0 release in February 2018 so now filtering is done first and scaling according to the results. Please note that the scaling factor is based on an estimate of how many reads will remain after filtering. This is accurate enough in ChIP-seq, but if you ever do something like targeted RNA-seq the estimate may be off due to not sampling enough of the genome.
